define({
	root: {
		areYouSure: 'Are You Sure?',
		cancel: 'Cancel',
		create: 'Create',
		addFeed: 'Add Feed',
		addFolder: 'Add Folder',
		date: 'Date',
		defaultFeedSettings: 'Default Feed Settings',
		defaultFeedSettingsDescription: 'These can be overridden on a per-feed basis in the feed settings.',
		delete: 'Delete',
		deleteFeedPrompt: 'Deleting this feed will remove it and all of its articles.',
		deleteFolderPrompt: 'Deleting this folder will also delete all child folders and feeds!',
		editFeed: 'Edit Feed',
		editFolder: 'Edit Folder',
		feedUrl: 'Feed URL',
		findArticles: 'Find Articles',
		folderName: 'Folder Name',
		makeTopLevel: 'Make Top-level',
		maxArticles: 'Maximum Articles',
		move: 'Move',
		name: 'Name',
		newFeed: 'New Feed',
		newFolder: 'New Folder',
		no: 'No',
		overrides: 'Overrides',
		parentFolder: 'Parent Folder',
		pinned: 'Pinned',
		preferences: 'Preferences',
		save: 'Save',
		search: 'Search',
		searchQuery: 'Search Query (supports RegExp)',
		searchResults: 'Search Results',
		showImages: 'Show Images',
		title: 'Title',
		unread: 'Unread',
		updateInterval: 'Update Interval',
		yes: 'Yes'
	}
});
