define({
  root: {
    addFeed: "Add Feed",
    addFolder: "Add Folder",
    areYouSure: "Are You Sure?",
    articles: "Articles",
    cancel: "Cancel",
    create: "Create",
    date: "Date",
    defaultFeedSettings: "Default Feed Settings",
    defaultFeedSettingsDescription:
      "These can be overridden on a per-feed basis in the feed settings.",
    delete: "Delete",
    deleteFeedPrompt: "Deleting this feed will remove it and all of its articles.",
    deleteFolderPrompt: "Deleting this folder will also delete all child folders and feeds!",
    downloadCompletePage: "Download complete page to read offline",
    downloading: "Downloading...",
    editFeed: "Edit Feed",
    editFolder: "Edit Folder",
    feeds: "Feeds",
    feedUrl: "Feed URL",
    findArticles: "Find Articles",
    folderName: "Folder Name",
    makeTopLevel: "Make Top-level",
    maxArticles: "Maximum Articles",
    move: "Move",
    name: "Name",
    newFeed: "New Feed",
    newFolder: "New Folder",
    no: "No",
    openArchivedPage: "Open archived page",
    overrides: "Overrides",
    parentFolder: "Parent Folder",
    pinned: "Pinned",
    preferences: "Preferences",
    regionSizes: "Region Sizes (in Percent)",
    save: "Save",
    search: "Search",
    searchQuery: "Search Query (supports RegExp)",
    searchResults: "Search Results",
    showImages: "Show Images",
    title: "Title",
    unread: "Unread",
    updateInterval: "Update Interval",
    yes: "Yes",
  },
});
